namespace ShinhanAPI.Object
{
    /// <summary>
    /// 현물 마스터
    /// </summary>
    public class SB
    {
        public string 표준코드 { get; set; }
        public string 단축코드 { get; set; }
        public string 장구분 { get; set; }
        public string 일련번호 { get; set; }
        public string 입회일자 { get; set; }
        public string 한글종목명 { get; set; }
        public string 영문종목명 { get; set; }
        public string 제조업구분_업종대분류 { get; set; }
        public string 업종중분류 { get; set; }
        public string 업종소분류 { get; set; }
        public string 산업업종코드 { get; set; }
        public string KOSPI200_KOSDAQ50채용구분 { get; set; }
        public string KOSPI100채용구분 { get; set; }
        public string KOSPI50채용구분 { get; set; }
        public string 정보통신지수채용구분 { get; set; }
        public string 시가총액규모_지수업종그룹 { get; set; }
        public string KOSDI구분_지배구조우량구분 { get; set; }
        public string 상장구분 { get; set; }
        public string 상장주식수 { get; set; }
        public string 소속구분 { get; set; }
        public string 결산월일 { get; set; }
        public string 액면가 { get; set; }
        public string 액면가변경구분코드 { get; set; }
        public string 전일종가 { get; set; }
        public string 전일거래량 { get; set; }
        public string 전일거래대금 { get; set; }
        public string 기준가 { get; set; }
        public string 상한가 { get; set; }
        public string 하한가 { get; set; }
        public string 대용가 { get; set; }
        public string 거래정지구분 { get; set; }
        public string 관리구분 { get; set; }
        public string 감리구분 { get; set; }
        public string 락구분 { get; set; }
        public string 불성실공시지정여부 { get; set; }
        public string 평가가격 { get; set; }
        public string 최고호가가격 { get; set; }
        public string 최저호가가격 { get; set; }
        public string 매매구분 { get; set; }
        public string 정리매매시작일 { get; set; }
        public string 정리매매종료일 { get; set; }
        public string 투자유의구분 { get; set; }
        public string REITs구분 { get; set; }
        public string 매매수량단위 { get; set; }
        public string 시간외매매수량단위 { get; set; }
        public string 자본금 { get; set; }
        public string 배당수익률 { get; set; }
        public string ETF분류 { get; set; }
        public string ETF관련지수업종대 { get; set; }
        public string ETF관련지수업종중 { get; set; }
        public string ETFCU단위 { get; set; }
        public string ETF구성종목수 { get; set; }
        public string ETF순자산총액 { get; set; }
        public string ETF관련지수대비비율 { get; set; }
        public string 최종NAV { get; set; }
        public string 매매방식구분 { get; set; }
        public string 통합지수종목구분 { get; set; }
        public string 매매개시일 { get; set; }
        public string KRX섹터지수자동차구분 { get; set; }
        public string KRX섹터지수반도체구분 { get; set; }
        public string KRX섹터지수바이오구분 { get; set; }
        public string KRX섹터지수금융구분 { get; set; }
        public string KRX섹터지수정보통신구분 { get; set; }
        public string 우회상장구분 { get; set; }
        public string KOSPI여부 { get; set; }
        public string KRX섹터지수화학에너지구분 { get; set; }
        public string KRX섹터지수철강구분 { get; set; }
        public string KRX섹터지수필수소비재구분 { get; set; }
        public string KRX섹터지수미디어통신구분 { get; set; }
        public string KRX섹터지수건설구분 { get; set; }
        public string KRX섹터지수비은행금융구분 { get; set; }
        public string 국가코드 { get; set; }
        public string 적용화폐단위 { get; set; }
        public string 적용환율 { get; set; }
        public string 투자위험예고여부 { get; set; }
        public string ETF유통주식수 { get; set; }
        public string ETF자산기준통화 { get; set; }
        public string ETF순자산총액_외화_ { get; set; }
        public string ETF유통순자산총액_원화_ { get; set; }
        public string ETF유통순자산총액_외화_ { get; set; }
        public string ETF최종NAV_외화_ { get; set; }
        public string KRX섹터지수증권구분 { get; set; }
        public string KRX섹터지수조선구분 { get; set; }
        public string 장전시간외시장가능여부 { get; set; }
        public string 공매도가능여부 { get; set; }
        public string ETF추적기초자산단위코드 { get; set; }
        public string ETF추적수익률배수부호 { get; set; }
        public string ETF추적수익률배수 { get; set; }
        public string ETF장외파생상품편입여부 { get; set; }
        public string ETF추적기초자산국내외구분코드 { get; set; }
        public string 상장일자 { get; set; }
        public string 발행가격 { get; set; }
        public string SRI지수여부 { get; set; }
        public string ETF참고지수소속시장구분코드 { get; set; }
        public string ETF참고지수업종코드 { get; set; }
        public string KRX섹터지수보험구분 { get; set; }
        public string KRX섹터지수운송구분 { get; set; }
        public string REGULATIONS적용여부 { get; set; }
        public string 일련번호8자리 { get; set; }
    }
}